version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - 'db'
    ports:
      - "3000:3000"

  db:
    image: postgres:12
    restart: always
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"




