version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - 'db'
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:11
    restart: always
    volumes:
      - .docker/db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airbnb_development
#    ports:
#      - "54320:5432"


