default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  host: db
  port: 54320
  database: <%= ENV['DATABASE_NAME'] || "airbnb_development" %>

test:
  <<: *default
  database: airbnb_test

production:
  <<: *default
  database: airbnb_production
  username: airbnb
  password: <%= ENV['AIRBNB_DATABASE_PASSWORD'] %>
